# Generated by Django 4.1.3 on 2022-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0005_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
