# Generated by Django 4.1.1 on 2022-12-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0008_alter_orderproduct_order_alter_orderproduct_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_by',
            new_name='user',
        ),
    ]
