# Generated by Django 4.1.1 on 2022-12-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0009_rename_created_by_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='createdd_by',
        ),
    ]
