# Generated by Django 4.1.1 on 2022-12-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0010_rename_user_order_createdd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdd_by',
            new_name='created_by',
        ),
    ]
