# Generated by Django 4.1.1 on 2022-12-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('el_shops', '0011_rename_createdd_by_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
