# Generated by Django 4.1.1 on 2022-12-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0014_rename_user_order_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
    ]
