# Generated by Django 4.1.1 on 2022-12-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0015_rename_product_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
