# Generated by Django 4.1.1 on 2022-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_shops', '0016_rename_product_id_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='el_shops.OrderProduct', to='el_shops.product'),
        ),
    ]
